version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    stdin_open: true 
    tty: true
#    depends_on:
#      db:
#        condition: service_healthy
    volumes:
    - .:/usr/src/app
###
#  db:
#    image: postgres:16.4-alpine3.20
#    environment:
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: auth
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d auth"]
#      interval: 2s
#      retries: 5
#      start_period: 10s
#      timeout: 2s

volumes:
#  pgdata:
  api: